/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/t-shirt.glb 
Author: Dreira091 (https://sketchfab.com/Dreira091)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-97d508268ed942ed89007023eede821b
Title: T-shirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/t-shirt.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.22}>
        <group position={[0, 6.245, -0.094]} scale={0.006}>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_5.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Object_7.geometry} material={materials['Material.005']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/t-shirt.glb')
